### ISSUE TITLE
Trying to run the project

### ISSUE THREAD

**Issue by kapeel45** [dharmapoudel/WebStore-Spring-MVC#1]
i tried to run the project but some cross sign i came across and while running it says... java facet 1.8 required

**Comment by dharmapoudel** [comment]
I've updated the project with import and build instruction. Please check the readme file and let me know if it works.

**Comment by sudvid78** [comment]
Hi,
i imported this as "Existing maven project" , now, how could I run this via Tomcat. pls. help

**Comment by dharmapoudel** [comment]
Which IDE are you using? If you are using eclipse go to project > properties > project facets> runtimes tab and add server from there. Now you can choose that server when you are doing run as.

**Comment by parkerqian** [comment]
hi,dharmapoudel
I have not see any database connection from your code , i am not sure which you are using ,mybatis or herbinate?

**Comment by parkerqian** [comment]
![11](https://cloud.githubusercontent.com/assets/4987818/12544489/7d9fa41e-c375-11e5-8f76-b4e9c2d3c36c.png)

**Comment by ujjwalit** [comment]
when i run the project its only showing welcome message no links or login page to go further

**Comment by ujjwalit** [comment]
i am running it on eclipse with tomcat 8

**Comment by dharmapoudel** [comment]
If you are seeing welcome message then its working. Now you just have to go to the specific urls yourself by manually entering them. Like /login to go to login page, /product/all to go to product list. 
Just go through the controllers and get some idea.

**Comment by dharmapoudel** [comment]
And adding link on the page should be pretty easy. To get some idea check links in products.jsp  page.

**Comment by ujjwalit** [comment]
No other links are working other than login and login page also don't redirect to any other page

Sent from Outlook Mobile

On Tue, Mar 15, 2016 at 10:12 AM -0700, "Dharma Poudel" notifications@github.com wrote:

And adding link on the page should be pretty easy. To get some idea check links in products.jsp  page.

---

**Comment by dharmapoudel** [comment]
Everything works as intended, tried and tested by me. You just need to read code in detail. For login try the username/passwords specified in spring security.

**Comment by jigyasu2010** [comment]
Hey i have added this code in my eclipse, i'm using java 8 and tomcat 7. It is not running on my server can you please tell me why it is not running..?
Can i show my code to you on skype call or Webex?
