### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by EnockPrince** [dharmapoudel/WebStore-Spring-MVC#5]
Hi Dharma,

Thank you for the efforts.. I am able to build successfully as you suggested. I have installed Mysql and Tomcat webserver in my machine. When i run the application it gives 500 error code. There is no details available in Read me about DB creation and tables. Since i am not a java engineer its really tough to understand the coading and all. Please provide step by step details.

Thank you...

**Comment by sandip-narwade** [comment]
Hello I need a db.sql file

**Comment by dharmapoudel** [comment]
you should be able to run using in memory db without sql.

**Comment by sandipnd31** [comment]
I will try sir
